src/types.ts
=> fix: Update avatargroup props

src/components/PagerView/PagerView.tsx, src/components/__tests__/__snapshots__/pagerview.test.js.snap
Added zIndex to PagerView headerConteiner style.
fix: #3
=> fix: PagerView Header Text visible

src/components/Slider/index.tsx
Fixed issue with the slider component printing warnings to the console.
fix: #13
=> fix: Problem with the slider component printing warnings to the console.

src/components/Dropdown/MultipleSelectDropdown.tsx
displaybuttonvalue was not working correctly when it received an object. This problem was solved by adding a new state and function.
fix: #16 
Necessary data was entered into the data prop of the multiple dropdown component. Selection and deselection operations were applied. Made sure that the displaybuttonvalue prop is working correctly.
=> fix: updated multiple dropdown menu displayButtonValue prop

src/types.ts
AvatarGroups size prop is deleted.
fix : #52
=> Update avatargroup props

src/components/SpeedDial/SpeedDial.tsx, src/types.ts
SpeedDial onChange prop is added.
close: #50
=> SpeedDial onChange prop is added

src/components/AccordionList/AccordionList.tsx, src/types.ts
Changed the requirements for "AccordionList" props.
fix: #55
=> fix: Changed the requirement of the AccordionList onExpand prop

src/components/ToggleButton/ToggleButton.tsx, yarn.lock
=> fix: The borderwidth style of the ToggleButton component now appears.

src/components/Button/Button.tsx, src/types.ts
=> fix: The text color now changes when the button is pressed

src/components/CheckBox/CheckBox.tsx
=> feat: Added style for CheckBox disabled prop

src/components/TextInput/TextInput.tsx
=> fix: Now helper text and count text styles are compatible

src/components/Menu/Menu.tsx
=> fix: Fixed press animation in the menu. Now works by default.

src/core/KitraProvider.tsx
=> fix: Fixed the issue where the text showing the percentage in the slider component did not show the correct value

src/components/Swipe/index.tsx
=> fix: actionText color dynamically updated

src/components/TextInput/TextInput.tsx, src/components/__tests__/__snapshots__/textinput.test.js.snap
=> fix: TextInput default background color added

src/components/Avatar/Avatar.tsx, src/components/__tests__/__snapshots__/avatar.test.js.snap
=> fix: The default value of the borderStyle prop is set to circular'

src/components/Menu/Menu.tsx, src/components/__tests__/__snapshots__/menu.test.js.snap
fix: #41 
The static width given to the menu has been dynamically updated.
=> fix: Menu static width deleted

src/components/ToggleButton/ToggleButton.tsx
=> fix: update opacity import

src/components/Menu/Menu.tsx, src/types.ts
=> refactor: Changed the labelStyle prop of the menu component to rowTextStyle

src/components/TextInput/TextInput.tsx, src/components/__tests__/__snapshots__/textinput.test.js.snap
=> fix: Fixed textinput component overlapping with border label.

src/components/Badge/Badge.tsx, src/types.ts
- badgeStyle prop added.
- Code optimization.
=> refactor: Code optimization of the badge component.

.eslintrc.json, example/src/screens/Menu.jsx, example/src/screens/PagerView.jsx, package.json, src/components/PagerView/PagerView.tsx, src/types.ts, yarn.lock
- pagerview dependency removed, now using flatlist.
=> refactor: pagerview

src/core/KitraProvider.tsx, src/core/hooks/useComponentTheme.tsx, src/types.ts
- removed unused theme consumer
=> fix: updated theme prop as optional

src/components/Dropdown/Dropdown.tsx
- fixed misspelled variable name
=> fix: dropdown dynamic height

src/components/Dropdown/MultipleSelectDropdown.tsx
- Fixed position errors of right and left props in the multiple dropdown.
- Fixed error “Each child in the list must have a unique key attribute”.
=> fix:Fixed position errors of right and left props in the multiple dropdown.

src/core/KitraProvider.tsx, src/core/notification/notification.tsx
Now you can write your own design in the notification with customView prop.
=> feat: Custom notification prop added.

doc/docs/doc/Theme.md, doc/docs/doc/getting-started.md
- update getting started install links
- update color palette
- add component theme system
=> update theme doc

src/components/Dropdown/Dropdown.tsx, src/components/Dropdown/MultipleSelectDropdown.tsx
feat: Enhance Dropdown component with modal support and improved visibility handling
=> fix: dropdown visibility; add value prop
